### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by mcrumm** [fastnorth/property-mapper#4]
First off, thank you for creating this, it's super helpful!

Is the project still being maintained?  I opened PR #3 to fix the currently outstanding issues, and I have ideas for some additional improvements, but I wanted to make sure this was still being developed before I submitted anything else.

**Comment by naneau** [comment]
Hi @mcrumm this project is very much still alive! I have merged #3 and will release a new version with it.

**Comment by mcrumm** [comment]
Thanks!  Are you open to additional PR's, as well? I'd like to make it easier to add custom mapping types without having to override the mapper.
