### ISSUE TITLE
Update Symfony Property Access

### ISSUE THREAD

**Issue by ghost** [fastnorth/property-mapper#5]
Symfony 3 by default requires a higher version of `symfony/property-access`, which generates the infamous *requirements could not be resolved to an installable set of packages* error.

I've changed  `"symfony/property-access": "^2.7"` to `"symfony/property-access": "^3.1"` ([latest version](http://symfony.com/doc/current/components/property_access.html)) locally and all tests still pass.

Should I open a PR to have `composer.json` updated accordingly?

Thanks.

**Comment by naneau** [comment]
I think this component is largely BC, so we can include both the 2 and 3 branch using the `|` separator in the composer dep.
